eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.31.100:8761}/eureka
  
  instance:
      instanceId: ${DOMAIN_NAME:localhost}:${random.value}
      hostname: ${DOMAIN_NAME:localhost}